apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ptapp.fullname" . }}-app-dev-conf
  labels:
    release: {{ .Release.Name }}
data:
  application-dev.yml: |
    spring:
      datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: {{ .Values.data.datasource.url }}
        username: {{ .Values.data.datasource.username }}
        password: {{ .Values.data.datasource.password }}
        driver-class-name: com.mysql.jdbc.Driver
        druid:
          # 初始化大小
          initial-size: 5
          # 最小
          min-idle: 5
          # 最大
          max-active: 100
          # 配置获取连接等待超时的时间
          max-wait: 60000
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          time-between-eviction-runs-millis: 60000
          # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
          min-evictable-idle-time-millis: 300000
          validationQuery: select 'x'
          # 当连接空闲时，是否执行连接测试
          test-while-idle: true
          # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
          filters: config,wall,stat
          # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
          connectionProperties: druid.stat.slowSqlMillis=200;druid.stat.logSlowSql=true;config.decrypt=false
          web-stat-filter:
            #是否启用StatFilter默认值true
            enabled: true
            url-pattern: /*
            exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,*.html,/static/*
            session-stat-enable: true
            session-stat-max-count: 10
          #StatViewServlet配置
          stat-view-servlet:
            #是否启用StatViewServlet默认值true
            enabled: true
    
      jpa:
    #    properties:
    #      hibernate:
    #        dialect: org.hibernate.dialect.DmDialect
        show-sql: true
        data:
          redis:
            repositories:
              enabled: false
      redis:
        host: {{ .Values.data.redis.host }}
        port: {{ .Values.data.redis.port }}
        password: {{ .Values.data.redis.password }}
        timeout: 10000
        lettuce:
          pool:
            max-idle: 10
            max-active: 10
            min-idle: 5
            max-wait: 10000
        database: 0
      servlet:
        multipart:
          max-file-size: 1024MB
          max-request-size: 1024MB
          file-size-threshold: 10MB
    
    management:
      endpoints:
        web:
          exposure:
            include: health,env,metrics
      endpoint:
        health:
          show-details: always
      health:
        redis:
          enabled: false
    
    logging:
      level:
        com.css.bpm.platform: debug
    
    swagger:
      enable: true
    
    
    server:
      servlet:
        context-path: /
