{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ptapp.serviceAccountName" . }}
  labels:
{{ include "ptapp.labels" . | nindent 4 }}
{{- end -}}
